### PR TITLE
2.0.0

### PR DESCRIPTION
**Pull request by jongacnik**
Hallo!

I've been working on a new choo project which is quite far along. I _love_ the v5 API, but was running into some weirdness with nanocomponent + nanomorph (I can provide some notes about that over in the choo repo). I'm on a very tight deadline and am too lazy to rewrite stuff, so I decided to see if just swapping out morphdom/bel/microcomponent with preact would work for my needs in this project. Aaaaaaand it did!

It worked so well, actually, that I thought I'd tidy it up and publish here since it might be handy for others? 2.0.0 is essentially a fork of current choo. The API is identical, with a couple additional aliases to preact methods for creating components. I've documented all this in the readme.

It's a pretty exact swap-out. All current choo examples and tests passed out of the box with like 0 modifications!

Direct link to branch: [https://github.com/jongacnik/rooch/tree/2.0.0](https://github.com/jongacnik/rooch/tree/2.0.0)

All best, huge thanks for your great work.

### CODE REVIEW

**Comment by jongacnik** [comment]
Also an example of rendering a react component eZ

Demo: https://rooch-react.glitch.me
Code: https://glitch.com/edit/#!/rooch-react

**Comment by developit** [comment]
This looks awesome @jongacnik. Makes sense to have rooch keep up with choo updates for sure.  For the size number - is that gzipped?

**Comment by jongacnik** [comment]
@developit yep, it's due to https://github.com/developit/preact-render-to-string to keep consistent API with choo, but I actually didn't realize just how much larger that was making it. Removed it for a quick test and module size went from 8.6kb -> 5.9kb.

Maybe we could veer from the API slightly and instead of `toString()` rooch has `toVnode()` which you could then use in combo w/ preact-render-to-string on your own?

**Comment by developit** [comment]
FWIW I think I can drop some weight from preact-render-to-string.  It is sortof two libraries in one - an HTML/XML renderer for this use-case, and a JSX String renderer used by assertion libraries like preact-jsx-chai.  Right now there seems to be a few functions in the base render-to-string library that are only useful for the JSX case, which has its own entrypoint.  I can split them out and codegolf the lib a bit to get things back down.

BTW - I'm seeing preact-render-to-string as around 2.6kb unminified - are you checking sizes after uglifyjs has been applied, or just direct?

**Comment by jongacnik** [comment]
Oh nice! Ya, I think splitting up would be great in cases like this. Maybe we just keep `toString()` in here for now to keep API parity, and then if ever get a chance to wiggle out that code at some point we can get some bytes back.

The sizes are just based on what the build script spits out with and without preact-render-to-string. I didn’t actually make any adjustments to how that’s compiled from choo: https://github.com/jongacnik/rooch/blob/2.0.0/package.json#L7. Uglify is applied, but maybe some tree-shaking isn’t happening?

**Comment by developit** [comment]
Seems like a reasonable setup, just isn't doing DCE as you said.  I think we should move forward with this as-is for now and we'll get the size cuts from upstream as they come in.

**Comment by jongacnik** [comment]
@developit should we publish this to npm as well?

**Comment by developit** [comment]
Yup, will be a bit before I can get around to it.  If @yoshuawuyts adds you to the npm project you can do it though!

**Comment by yoshuawuyts** [comment]
done! :tada:

**Pull request merged**
